// lib/email/digest.ts
/**
 * Email sending for weekly digests using Resend
 */

import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

interface DigestEmailData {
  summary: string;
  topThemes: Array<{ theme: string; weight: number }>;
  openLoops: Array<{ conversation_id: string; conversation_title: string | null; snippet: string }>;
  weekStart: string;
  weekEnd: string;
  userName?: string;
  digestUrl?: string;
}

/**
 * Generate HTML email template for weekly digest
 */
function generateDigestEmailHTML(data: DigestEmailData): string {
  const themesHTML = data.topThemes.length > 0
    ? `
      <div style="margin: 24px 0;">
        <h3 style="font-size: 18px; font-weight: 600; margin-bottom: 12px; color: #18181b;">Top Themes</h3>
        <ul style="list-style: none; padding: 0; margin: 0;">
          ${data.topThemes.map((theme) => `
            <li style="margin: 8px 0; padding: 8px; background: #f4f4f5; border-radius: 4px;">
              <strong style="color: #18181b;">${theme.theme}</strong>
              <span style="color: #71717a; font-size: 14px; margin-left: 8px;">
                (${Math.round(theme.weight * 100)}%)
              </span>
            </li>
          `).join('')}
        </ul>
      </div>
    `
    : '';

  const openLoopsHTML = data.openLoops.length > 0
    ? `
      <div style="margin: 24px 0;">
        <h3 style="font-size: 18px; font-weight: 600; margin-bottom: 12px; color: #18181b;">Open Loops</h3>
        <ul style="list-style: none; padding: 0; margin: 0;">
          ${data.openLoops.map((loop) => `
            <li style="margin: 12px 0; padding: 12px; background: #fef3c7; border-left: 3px solid #f59e0b; border-radius: 4px;">
              <strong style="color: #18181b; display: block; margin-bottom: 4px;">
                ${loop.conversation_title || 'Untitled Conversation'}
              </strong>
              <p style="color: #52525b; font-size: 14px; margin: 0;">${loop.snippet}</p>
            </li>
          `).join('')}
        </ul>
      </div>
    `
    : '';

  const viewDigestLink = data.digestUrl
    ? `
      <div style="margin: 24px 0; text-align: center;">
        <a href="${data.digestUrl}" style="display: inline-block; padding: 12px 24px; background: #18181b; color: #ffffff; text-decoration: none; border-radius: 6px; font-weight: 500;">
          View Full Digest
        </a>
      </div>
    `
    : '';

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
      </head>
      <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #18181b; background: #ffffff; margin: 0; padding: 0;">
        <div style="max-width: 600px; margin: 0 auto; padding: 24px;">
          <div style="margin-bottom: 24px;">
            <h1 style="font-size: 24px; font-weight: 600; margin: 0; color: #18181b;">Your Weekly INDEX Digest</h1>
            <p style="color: #71717a; font-size: 14px; margin: 8px 0 0 0;">
              ${new Date(data.weekStart).toLocaleDateString()} - ${new Date(data.weekEnd).toLocaleDateString()}
            </p>
          </div>

          <div style="background: #f4f4f5; padding: 20px; border-radius: 8px; margin: 24px 0;">
            <h2 style="font-size: 18px; font-weight: 600; margin: 0 0 12px 0; color: #18181b;">Summary</h2>
            <div style="color: #52525b; white-space: pre-wrap;">${data.summary}</div>
          </div>

          ${themesHTML}
          ${openLoopsHTML}
          ${viewDigestLink}

          <div style="margin-top: 32px; padding-top: 24px; border-top: 1px solid #e4e4e7; text-align: center;">
            <p style="color: #71717a; font-size: 12px; margin: 0;">
              This digest was generated by INDEX. Your conversations are private and never used to train AI models.
            </p>
          </div>
        </div>
      </body>
    </html>
  `;
}

/**
 * Send weekly digest email
 */
export async function sendDigestEmail(
  to: string,
  data: DigestEmailData
): Promise<{ success: boolean; messageId?: string; error?: string }> {
  try {
    if (!process.env.RESEND_API_KEY) {
      throw new Error('RESEND_API_KEY not configured');
    }

    const fromEmail = process.env.RESEND_FROM_EMAIL || 'INDEX <noreply@indexapp.co>';

    const result = await resend.emails.send({
      from: fromEmail,
      to,
      subject: `Your Weekly INDEX Digest: ${new Date(data.weekStart).toLocaleDateString()} - ${new Date(data.weekEnd).toLocaleDateString()}`,
      html: generateDigestEmailHTML(data),
    });

    if (result.error) {
      throw new Error(result.error.message || 'Failed to send email');
    }

    return {
      success: true,
      messageId: result.data?.id,
    };
  } catch (error) {
    console.error('Send digest email error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to send email',
    };
  }
}

