// app/components/StartChatModal.tsx
'use client';

import { useState, useEffect } from 'react';
import { ContextBlock } from '@/lib/contextGenerator';

interface StartChatModalProps {
  isOpen: boolean;
  onClose: () => void;
  contextBlock: ContextBlock;
  runId?: string | null;
  onStatusUpdate?: (status: 'copied' | 'harvested' | 'abandoned') => void;
  mode?: 'intent-selector' | 'prompt-viewer';
  onGenerate?: (intent: string, targetTool: string) => Promise<{ promptText: string; runId: string } | void>;
  projectName?: string;
}

const CHAT_DESTINATIONS = {
  chatgpt: {
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    icon: '🤖',
  },
  claude: {
    name: 'Claude',
    url: 'https://claude.ai',
    icon: '🧠',
  },
  cursor: {
    name: 'Cursor',
    url: 'https://cursor.sh',
    icon: '⌨️',
  },
};

const INTENT_DESCRIPTIONS: Record<string, string> = {
  decide_between_options: 'Decide between options',
  generate_next_actions: 'Generate next concrete actions',
  resolve_blocking_uncertainty: 'Resolve a blocking uncertainty',
  produce_plan_architecture: 'Produce a plan / architecture',
  stress_test_direction: 'Stress-test current direction',
  summarize_state_propose_path: 'Summarize state → propose path forward',
};

export default function StartChatModal({
  isOpen,
  onClose,
  contextBlock,
  runId: initialRunId,
  onStatusUpdate,
  mode = 'prompt-viewer',
  onGenerate,
  projectName,
}: StartChatModalProps) {
  const [copied, setCopied] = useState(false);
  const [selectedIntent, setSelectedIntent] = useState<string>('decide_between_options');
  const [customIntent, setCustomIntent] = useState('');
  const [targetTool, setTargetTool] = useState<'chatgpt' | 'claude' | 'cursor' | 'other'>('chatgpt');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  // Internal state for 2-step flow
  const [modalMode, setModalMode] = useState<'configure' | 'ready'>('configure');
  const [generatedPrompt, setGeneratedPrompt] = useState<string | null>(null);
  const [generatedRunId, setGeneratedRunId] = useState<string | null>(initialRunId || null);
  const [isExpanded, setIsExpanded] = useState(false);

  useEffect(() => {
    if (!isOpen) {
      setCopied(false);
      setModalMode('configure');
      setGeneratedPrompt(null);
      setIsExpanded(false);
      setError(null);
    }
  }, [isOpen]);

  const handleCopy = async () => {
    try {
      let textToCopy = generatedPrompt || contextBlock.fullContext;
      
      // Add watermark if project name is available
      if (projectName) {
        const timestamp = new Date().toLocaleString();
        textToCopy += `\n\n---\nGenerated by INDEX — ${projectName} — ${timestamp}`;
      }
      
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      
      // Update status to 'copied' if runId exists
      const currentRunId = generatedRunId || initialRunId;
      if (currentRunId) {
        // Call API to update status
        try {
          await fetch(`/api/start-chat/${currentRunId}/update-status`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ status: 'copied' }),
          });
        } catch (apiErr) {
          console.error('Failed to update status:', apiErr);
        }
        
        // Also call callback if provided
        if (onStatusUpdate) {
          onStatusUpdate('copied');
        }
      }
      
      // Track prompt copied event
      const { trackEvent } = await import('@/lib/analytics');
      trackEvent('prompt_copied', {
        target_tool: targetTool,
        has_run_id: !!currentRunId,
      });
    } catch (err) {
      console.error('Failed to copy to clipboard:', err);
    }
  };

  const handleOpenDestination = async (url: string) => {
    // Copy context to clipboard first
    try {
      let textToCopy = generatedPrompt || contextBlock.fullContext;
      
      // Add watermark if project name is available
      if (projectName) {
        const timestamp = new Date().toLocaleString();
        textToCopy += `\n\n---\nGenerated by INDEX — ${projectName} — ${timestamp}`;
      }
      
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      
      // Update status to 'copied' if runId exists
      const currentRunId = generatedRunId || initialRunId;
      if (currentRunId) {
        // Call API to update status
        try {
          await fetch(`/api/start-chat/${currentRunId}/update-status`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ status: 'copied' }),
          });
        } catch (apiErr) {
          console.error('Failed to update status:', apiErr);
        }
        
        // Also call callback if provided
        if (onStatusUpdate) {
          onStatusUpdate('copied');
        }
      }
    } catch (err) {
      console.error('Failed to copy to clipboard:', err);
    }
    
    // Open destination in new tab
    window.open(url, '_blank');
  };

  const handleGenerate = async () => {
    if (!onGenerate) return;
    
    const intent = selectedIntent === 'custom' ? customIntent : selectedIntent;
    if (!intent || intent.trim().length === 0) {
      setError('Please select or enter an intent');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      // Determine object type from contextBlock source
      // Note: This is approximate - contextBlock.source may not perfectly map to object_type
      let objectType: 'project' | 'task' | 'decision' = 'project';
      if (contextBlock.source === 'decision') {
        objectType = 'decision';
      }
      
      const result = await onGenerate(intent, targetTool);
      
      // Determine prompt length
      let promptLength = 0;
      if (result && typeof result === 'object' && 'promptText' in result) {
        promptLength = result.promptText.length;
      } else if (contextBlock.fullContext) {
        promptLength = contextBlock.fullContext.length;
      }
      
      // Track start chat invoked (after generation to capture actual prompt length)
      const { trackEvent } = await import('@/lib/analytics');
      trackEvent('start_chat_invoked', {
        target_tool: targetTool,
        intent_type: selectedIntent === 'custom' ? 'custom' : selectedIntent,
        object_type: objectType,
        has_project: !!contextBlock.project,
        prompt_length: promptLength,
      });
      
      // If onGenerate returns prompt data, use it; otherwise it's handled externally
      if (result && typeof result === 'object' && 'promptText' in result) {
        setGeneratedPrompt(result.promptText);
        if (result.runId) {
          setGeneratedRunId(result.runId);
        }
        setModalMode('ready');
      } else {
        // Legacy behavior: if onGenerate doesn't return data, assume it's handled externally
        // But we still switch to ready mode if we have fullContext
        if (contextBlock.fullContext) {
          setModalMode('ready');
        }
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate prompt');
    } finally {
      setLoading(false);
    }
  };

  const handleHarvest = () => {
    const currentRunId = generatedRunId || initialRunId;
    if (currentRunId && onStatusUpdate) {
      onStatusUpdate('harvested');
    }
    onClose();
  };

  const handleAbandon = () => {
    const currentRunId = generatedRunId || initialRunId;
    if (currentRunId && onStatusUpdate) {
      onStatusUpdate('abandoned');
    }
    onClose();
  };

  const handleBackToConfigure = () => {
    setModalMode('configure');
    setIsExpanded(false);
  };

  if (!isOpen) return null;

  // Determine which mode to show
  const showConfigure = mode === 'intent-selector' && modalMode === 'configure';
  const showReady = (mode === 'intent-selector' && modalMode === 'ready') || (mode === 'prompt-viewer' && contextBlock.fullContext);

  if (showConfigure) {
    return (
      <div
        className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 dark:bg-black/70"
        onClick={onClose}
      >
        <div
          className="bg-[rgb(var(--surface))] rounded-2xl p-6 max-w-lg w-full mx-4 shadow-xl ring-1 ring-[rgb(var(--ring)/0.12)]"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Optional tonal gradient header strip */}
          <div className="bg-gradient-to-br from-[rgb(var(--surface2))] to-[rgb(var(--surface))] -m-6 mb-4 p-6 rounded-t-2xl">
            <div className="flex items-center justify-between">
              <h2 className="font-serif text-xl font-semibold text-[rgb(var(--text))]">Resume</h2>
              <button
                onClick={onClose}
                className="text-[rgb(var(--muted))] hover:text-[rgb(var(--text))] transition-colors"
              >
                ✕
              </button>
            </div>
          </div>

          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-[rgb(var(--text))] mb-3">
                Intent (required)
              </label>
              <div className="space-y-2">
                {Object.entries(INTENT_DESCRIPTIONS).map(([key, label]) => (
                  <label
                    key={key}
                    className="flex items-center gap-2 p-2 rounded-lg hover:bg-[rgb(var(--surface2))] cursor-pointer transition-colors"
                  >
                    <input
                      type="radio"
                      name="intent"
                      value={key}
                      checked={selectedIntent === key}
                      onChange={(e) => {
                        setSelectedIntent(e.target.value);
                        setCustomIntent('');
                      }}
                      className="w-4 h-4 text-[rgb(var(--text))] focus:ring-2 focus:ring-[rgb(var(--ring)/0.2)]"
                    />
                    <span className="text-sm text-[rgb(var(--text))]">{label}</span>
                  </label>
                ))}
                <label className="flex items-center gap-2 p-2 rounded-lg hover:bg-[rgb(var(--surface2))] cursor-pointer transition-colors">
                  <input
                    type="radio"
                    name="intent"
                    value="custom"
                    checked={selectedIntent === 'custom'}
                    onChange={(e) => setSelectedIntent(e.target.value)}
                    className="w-4 h-4 text-[rgb(var(--text))] focus:ring-2 focus:ring-[rgb(var(--ring)/0.2)]"
                  />
                  <span className="text-sm text-[rgb(var(--text))]">Custom…</span>
                </label>
              </div>
            </div>

            {selectedIntent === 'custom' && (
              <div>
                <input
                  type="text"
                  value={customIntent}
                  onChange={(e) => setCustomIntent(e.target.value)}
                  placeholder="Describe your intent..."
                  className="w-full px-3 py-2 border border-[rgb(var(--ring)/0.12)] rounded-lg bg-[rgb(var(--surface))] text-[rgb(var(--text))] focus:outline-none focus:ring-2 focus:ring-[rgb(var(--ring)/0.2)]"
                />
              </div>
            )}

            <div>
              <label className="block text-sm font-medium text-[rgb(var(--text))] mb-2">
                Target Tool
              </label>
              <select
                value={targetTool}
                onChange={(e) => setTargetTool(e.target.value as typeof targetTool)}
                className="w-full px-3 py-2 border border-[rgb(var(--ring)/0.12)] rounded-lg bg-[rgb(var(--surface))] text-[rgb(var(--text))] focus:outline-none focus:ring-2 focus:ring-[rgb(var(--ring)/0.2)]"
              >
                <option value="chatgpt">ChatGPT</option>
                <option value="claude">Claude</option>
                <option value="cursor">Cursor</option>
                <option value="other">Other</option>
              </select>
            </div>

            {error && (
              <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
            )}

            <button
              onClick={handleGenerate}
              disabled={loading || (selectedIntent === 'custom' && !customIntent.trim())}
              className="w-full px-4 py-2 bg-[rgb(var(--text))] text-[rgb(var(--bg))] rounded-lg hover:opacity-90 transition-opacity font-medium disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? 'Generating...' : 'Generate Prompt'}
            </button>
          </div>
        </div>
      </div>
    );
  }

  // Ready mode: Show prompt preview and actions
  if (showReady) {
    const promptToShow = generatedPrompt || contextBlock.fullContext || '';
    const previewText = promptToShow.substring(0, 200) + (promptToShow.length > 200 ? '...' : '');
    const displayText = isExpanded ? promptToShow : previewText;

    return (
      <div
        className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 dark:bg-black/70"
        onClick={onClose}
      >
        <div
          className="bg-[rgb(var(--surface))] rounded-2xl p-6 max-w-2xl w-full mx-4 shadow-xl ring-1 ring-[rgb(var(--ring)/0.12)] max-h-[90vh] overflow-y-auto"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Optional tonal gradient header strip */}
          <div className="bg-gradient-to-br from-[rgb(var(--surface2))] to-[rgb(var(--surface))] -m-6 mb-4 p-6 rounded-t-2xl">
            <div className="flex items-center justify-between">
              <h2 className="font-serif text-xl font-semibold text-[rgb(var(--text))]">Resume</h2>
              <button
                onClick={onClose}
                className="text-[rgb(var(--muted))] hover:text-[rgb(var(--text))] transition-colors"
              >
                ✕
              </button>
            </div>
          </div>

          <div className="space-y-4">
            {/* Back to configure link */}
            <button
              onClick={handleBackToConfigure}
              className="text-sm text-[rgb(var(--muted))] hover:text-[rgb(var(--text))] transition-colors"
            >
              ← Edit intent
            </button>

            {/* Prompt Preview */}
            <div>
              <h3 className="text-sm font-medium text-[rgb(var(--text))] mb-2">Prompt Preview</h3>
              <div className="relative bg-[rgb(var(--surface2))] border border-[rgb(var(--ring)/0.08)] rounded-lg p-4 overflow-hidden">
                {/* Subtle intelligence texture */}
                <div 
                  className="absolute inset-0 opacity-[0.015] dark:opacity-[0.03] pointer-events-none"
                  style={{
                    backgroundImage: `
                      radial-gradient(circle at 1px 1px, currentColor 1px, transparent 0),
                      linear-gradient(90deg, transparent 0%, currentColor 1px, transparent 1px)
                    `,
                    backgroundSize: '20px 20px, 20px 20px',
                  }}
                />
                <pre className="relative text-xs text-[rgb(var(--text))] whitespace-pre-wrap break-words font-mono">
                  {displayText}
                </pre>
                {promptToShow.length > 200 && (
                  <button
                    onClick={() => setIsExpanded(!isExpanded)}
                    className="relative mt-2 text-xs text-[rgb(var(--muted))] hover:text-[rgb(var(--text))] transition-colors"
                  >
                    {isExpanded ? 'Collapse' : 'Expand details'}
                  </button>
                )}
              </div>
            </div>

            {error && (
              <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
            )}

            {/* Primary action: Copy Prompt */}
            <div className="flex justify-center">
              <button
                onClick={handleCopy}
                className="max-w-md w-full px-4 py-2 bg-[rgb(var(--text))] text-[rgb(var(--bg))] rounded-lg hover:opacity-85 transition-opacity font-medium flex items-center justify-center gap-2"
              >
                {copied ? (
                  <>
                    <span>✓</span>
                    <span>Copied!</span>
                  </>
                ) : (
                  <>
                    <span>📋</span>
                    <span>Copy Prompt</span>
                  </>
                )}
              </button>
            </div>

            {/* Secondary actions: Open in tools */}
            <div className="border-t border-[rgb(var(--ring)/0.08)] pt-4">
              <p className="text-sm font-medium text-[rgb(var(--text))] mb-3">
                Open in your chat tool:
              </p>
              <div className="grid grid-cols-3 gap-3">
                {Object.entries(CHAT_DESTINATIONS).map(([key, dest]) => (
                  <button
                    key={key}
                    onClick={() => handleOpenDestination(dest.url)}
                    className="px-4 py-3 border border-[rgb(var(--ring)/0.12)] rounded-lg hover:border-[rgb(var(--ring)/0.2)] hover:bg-[rgb(var(--surface2))] transition-colors text-sm font-medium text-[rgb(var(--text))] flex flex-col items-center gap-1"
                  >
                    <span className="text-lg">{dest.icon}</span>
                    <span>{dest.name}</span>
                  </button>
                ))}
              </div>
            </div>

            {/* Status update actions (if runId exists) */}
            {generatedRunId && onStatusUpdate && (
              <div className="border-t border-zinc-200 dark:border-zinc-800 pt-4 mt-4">
                <p className="text-xs text-zinc-500 dark:text-zinc-500 mb-2">
                  After using this in your chat tool:
                </p>
                <div className="flex gap-2">
                  <button
                    onClick={handleHarvest}
                    className="flex-1 px-3 py-2 text-xs bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-400 hover:bg-green-200 dark:hover:bg-green-900/50 rounded-lg transition-colors"
                  >
                    Mark Harvested
                  </button>
                  <button
                    onClick={handleAbandon}
                    className="flex-1 px-3 py-2 text-xs bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 hover:bg-zinc-200 dark:hover:bg-zinc-700 rounded-lg transition-colors"
                  >
                    Abandon
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    );
  }

  // Fallback: prompt-viewer mode (for non-Resume use cases)
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 dark:bg-black/70"
      onClick={onClose}
    >
      <div
        className="bg-[rgb(var(--surface))] rounded-2xl p-6 max-w-2xl w-full mx-4 shadow-xl ring-1 ring-[rgb(var(--ring)/0.12)]"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between mb-4">
          <h2 className="font-serif text-xl font-semibold text-[rgb(var(--text))]">Start Chat from This</h2>
          <button
            onClick={onClose}
            className="text-[rgb(var(--muted))] hover:text-[rgb(var(--text))] transition-colors"
          >
            ✕
          </button>
        </div>

        <div className="mb-6">
          <div className="bg-[rgb(var(--surface2))] border border-[rgb(var(--ring)/0.08)] rounded-lg p-4 mb-4">
            <p className="text-sm font-medium text-[rgb(var(--muted))] mb-2">
              Context generated from your INDEX memory:
            </p>
            {contextBlock.project && (
              <p className="text-sm text-[rgb(var(--text))] mb-1">
                <span className="font-medium">Project:</span> {contextBlock.project}
              </p>
            )}
            <p className="text-sm text-[rgb(var(--text))] mb-1">
              <span className="font-medium">Source:</span>{' '}
              {contextBlock.source === 'highlight' && 'Highlight'}
              {contextBlock.source === 'branch' && 'Branch'}
              {contextBlock.source === 'search_result' && 'Search Result'}
              {contextBlock.source === 'decision' && 'Decision'}
            </p>
            <p className="text-sm text-[rgb(var(--text))] mb-3">
              <span className="font-medium">Summary:</span> {contextBlock.summary}
            </p>
            <p className="text-sm text-[rgb(var(--text))]">
              <span className="font-medium">Suggested exploration:</span>{' '}
              {contextBlock.suggestedExploration}
            </p>
          </div>

          <button
            onClick={handleCopy}
            className="w-full px-4 py-2 bg-[rgb(var(--surface2))] hover:bg-[rgb(var(--surface))] rounded-lg text-sm font-medium text-[rgb(var(--text))] transition-colors flex items-center justify-center gap-2"
          >
            {copied ? (
              <>
                <span>✓</span>
                <span>Copied!</span>
              </>
            ) : (
              <>
                <span>📋</span>
                <span>Copy Context</span>
              </>
            )}
          </button>
        </div>

        <div className="border-t border-[rgb(var(--ring)/0.08)] pt-4">
          <p className="text-sm font-medium text-[rgb(var(--text))] mb-3">
            Open in your chat tool:
          </p>
          <div className="grid grid-cols-3 gap-3">
            {Object.entries(CHAT_DESTINATIONS).map(([key, dest]) => (
              <button
                key={key}
                onClick={() => handleOpenDestination(dest.url)}
                className="px-4 py-3 border border-[rgb(var(--ring)/0.12)] rounded-lg hover:border-[rgb(var(--ring)/0.2)] hover:bg-[rgb(var(--surface2))] transition-colors text-sm font-medium text-[rgb(var(--text))] flex flex-col items-center gap-1"
              >
                <span className="text-lg">{dest.icon}</span>
                <span>{dest.name}</span>
              </button>
            ))}
          </div>
        </div>

        <p className="text-xs text-[rgb(var(--muted))] mt-4 text-center">
          Context will be copied to your clipboard when you click a destination
        </p>

        {(generatedRunId || initialRunId) && (
          <div className="border-t border-[rgb(var(--ring)/0.08)] pt-4 mt-4">
            <p className="text-xs text-[rgb(var(--muted))] mb-2">
              After using this in your chat tool:
            </p>
            <div className="flex gap-2">
              <button
                onClick={handleHarvest}
                className="flex-1 px-3 py-2 text-xs bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-400 hover:bg-green-200 dark:hover:bg-green-900/50 rounded-lg transition-colors"
              >
                Mark Harvested
              </button>
              <button
                onClick={handleAbandon}
                className="flex-1 px-3 py-2 text-xs bg-[rgb(var(--surface2))] text-[rgb(var(--muted))] hover:bg-[rgb(var(--surface))] rounded-lg transition-colors"
              >
                Abandon
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

