// app/components/StartChatModal.tsx
'use client';

import { useState, useEffect } from 'react';
import { ContextBlock } from '@/lib/contextGenerator';

interface StartChatModalProps {
  isOpen: boolean;
  onClose: () => void;
  contextBlock: ContextBlock;
  runId?: string | null;
  onStatusUpdate?: (status: 'copied' | 'harvested' | 'abandoned') => void;
  mode?: 'intent-selector' | 'prompt-viewer';
  onGenerate?: (intent: string, targetTool: string) => Promise<void>;
  projectName?: string;
}

const CHAT_DESTINATIONS = {
  chatgpt: {
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    icon: '🤖',
  },
  claude: {
    name: 'Claude',
    url: 'https://claude.ai',
    icon: '🧠',
  },
  cursor: {
    name: 'Cursor',
    url: 'https://cursor.sh',
    icon: '⌨️',
  },
};

const INTENT_DESCRIPTIONS: Record<string, string> = {
  decide_between_options: 'Decide between options',
  generate_next_actions: 'Generate next concrete actions',
  resolve_blocking_uncertainty: 'Resolve a blocking uncertainty',
  produce_plan_architecture: 'Produce a plan / architecture',
  stress_test_direction: 'Stress-test current direction',
  summarize_state_propose_path: 'Summarize state → propose path forward',
};

export default function StartChatModal({
  isOpen,
  onClose,
  contextBlock,
  runId,
  onStatusUpdate,
  mode = 'prompt-viewer',
  onGenerate,
  projectName,
}: StartChatModalProps) {
  const [copied, setCopied] = useState(false);
  const [selectedIntent, setSelectedIntent] = useState<string>('decide_between_options');
  const [customIntent, setCustomIntent] = useState('');
  const [targetTool, setTargetTool] = useState<'chatgpt' | 'claude' | 'cursor' | 'other'>('chatgpt');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!isOpen) {
      setCopied(false);
    }
  }, [isOpen]);

  const handleCopy = async () => {
    try {
      let textToCopy = contextBlock.fullContext;
      
      // Add watermark if project name is available
      if (projectName) {
        const timestamp = new Date().toLocaleString();
        textToCopy += `\n\n---\nGenerated by INDEX — ${projectName} — ${timestamp}`;
      }
      
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      
      // Update status to 'copied' if runId exists
      if (runId && onStatusUpdate) {
        onStatusUpdate('copied');
      }
    } catch (err) {
      console.error('Failed to copy to clipboard:', err);
    }
  };

  const handleOpenDestination = async (url: string) => {
    // Copy context to clipboard first
    try {
      let textToCopy = contextBlock.fullContext;
      
      // Add watermark if project name is available
      if (projectName) {
        const timestamp = new Date().toLocaleString();
        textToCopy += `\n\n---\nGenerated by INDEX — ${projectName} — ${timestamp}`;
      }
      
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      
      // Update status to 'copied' if runId exists
      if (runId && onStatusUpdate) {
        onStatusUpdate('copied');
      }
    } catch (err) {
      console.error('Failed to copy to clipboard:', err);
    }
    
    // Open destination in new tab
    window.open(url, '_blank');
  };

  const handleGenerate = async () => {
    if (!onGenerate) return;
    
    const intent = selectedIntent === 'custom' ? customIntent : selectedIntent;
    if (!intent || intent.trim().length === 0) {
      setError('Please select or enter an intent');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      await onGenerate(intent, targetTool);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate prompt');
    } finally {
      setLoading(false);
    }
  };

  const handleHarvest = () => {
    if (runId && onStatusUpdate) {
      onStatusUpdate('harvested');
    }
    onClose();
  };

  const handleAbandon = () => {
    if (runId && onStatusUpdate) {
      onStatusUpdate('abandoned');
    }
    onClose();
  };

  if (!isOpen) return null;

  if (mode === 'intent-selector') {
    return (
      <div
        className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 dark:bg-black/70"
        onClick={onClose}
      >
        <div
          className="bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg p-6 max-w-lg w-full mx-4 shadow-xl"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl font-semibold text-foreground">Resume</h2>
            <button
              onClick={onClose}
              className="text-zinc-500 hover:text-foreground transition-colors"
            >
              ✕
            </button>
          </div>

          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-foreground mb-3">
                Intent (required)
              </label>
              <div className="space-y-2">
                {Object.entries(INTENT_DESCRIPTIONS).map(([key, label]) => (
                  <label
                    key={key}
                    className="flex items-center gap-2 p-2 rounded-lg hover:bg-zinc-50 dark:hover:bg-zinc-900 cursor-pointer"
                  >
                    <input
                      type="radio"
                      name="intent"
                      value={key}
                      checked={selectedIntent === key}
                      onChange={(e) => {
                        setSelectedIntent(e.target.value);
                        setCustomIntent('');
                      }}
                      className="w-4 h-4 text-foreground focus:ring-2 focus:ring-zinc-500 dark:focus:ring-zinc-400"
                    />
                    <span className="text-sm text-foreground">{label}</span>
                  </label>
                ))}
                <label className="flex items-center gap-2 p-2 rounded-lg hover:bg-zinc-50 dark:hover:bg-zinc-900 cursor-pointer">
                  <input
                    type="radio"
                    name="intent"
                    value="custom"
                    checked={selectedIntent === 'custom'}
                    onChange={(e) => setSelectedIntent(e.target.value)}
                    className="w-4 h-4 text-foreground focus:ring-2 focus:ring-zinc-500 dark:focus:ring-zinc-400"
                  />
                  <span className="text-sm text-foreground">Custom…</span>
                </label>
              </div>
            </div>

            {selectedIntent === 'custom' && (
              <div>
                <input
                  type="text"
                  value={customIntent}
                  onChange={(e) => setCustomIntent(e.target.value)}
                  placeholder="Describe your intent..."
                  className="w-full px-3 py-2 border border-zinc-300 dark:border-zinc-700 rounded-lg bg-white dark:bg-zinc-950 text-foreground focus:outline-none focus:ring-2 focus:ring-zinc-500 dark:focus:ring-zinc-400"
                />
              </div>
            )}

            <div>
              <label className="block text-sm font-medium text-foreground mb-2">
                Target Tool
              </label>
              <select
                value={targetTool}
                onChange={(e) => setTargetTool(e.target.value as typeof targetTool)}
                className="w-full px-3 py-2 border border-zinc-300 dark:border-zinc-700 rounded-lg bg-white dark:bg-zinc-950 text-foreground focus:outline-none focus:ring-2 focus:ring-zinc-500 dark:focus:ring-zinc-400"
              >
                <option value="chatgpt">ChatGPT</option>
                <option value="claude">Claude</option>
                <option value="cursor">Cursor</option>
                <option value="other">Other</option>
              </select>
            </div>

            {error && (
              <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
            )}

            <button
              onClick={handleGenerate}
              disabled={loading || (selectedIntent === 'custom' && !customIntent.trim())}
              className="w-full px-4 py-2 bg-foreground text-background rounded-lg hover:opacity-90 transition-opacity font-medium disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? 'Generating...' : 'Generate Prompt'}
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 dark:bg-black/70"
      onClick={onClose}
    >
      <div
        className="bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg p-6 max-w-2xl w-full mx-4 shadow-xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-xl font-semibold text-foreground">Start Chat from This</h2>
          <button
            onClick={onClose}
            className="text-zinc-500 hover:text-foreground transition-colors"
          >
            ✕
          </button>
        </div>

        <div className="mb-6">
          <div className="bg-zinc-50 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-lg p-4 mb-4">
            <p className="text-sm font-medium text-zinc-600 dark:text-zinc-400 mb-2">
              Context generated from your INDEX memory:
            </p>
            {contextBlock.project && (
              <p className="text-sm text-foreground mb-1">
                <span className="font-medium">Project:</span> {contextBlock.project}
              </p>
            )}
            <p className="text-sm text-foreground mb-1">
              <span className="font-medium">Source:</span>{' '}
              {contextBlock.source === 'highlight' && 'Highlight'}
              {contextBlock.source === 'branch' && 'Branch'}
              {contextBlock.source === 'search_result' && 'Search Result'}
              {contextBlock.source === 'decision' && 'Decision'}
            </p>
            <p className="text-sm text-foreground mb-3">
              <span className="font-medium">Summary:</span> {contextBlock.summary}
            </p>
            <p className="text-sm text-foreground">
              <span className="font-medium">Suggested exploration:</span>{' '}
              {contextBlock.suggestedExploration}
            </p>
          </div>

          <button
            onClick={handleCopy}
            className="w-full px-4 py-2 bg-zinc-100 dark:bg-zinc-800 hover:bg-zinc-200 dark:hover:bg-zinc-700 rounded-lg text-sm font-medium text-foreground transition-colors flex items-center justify-center gap-2"
          >
            {copied ? (
              <>
                <span>✓</span>
                <span>Copied!</span>
              </>
            ) : (
              <>
                <span>📋</span>
                <span>Copy Context</span>
              </>
            )}
          </button>
        </div>

        <div className="border-t border-zinc-200 dark:border-zinc-800 pt-4">
          <p className="text-sm font-medium text-foreground mb-3">
            Open in your chat tool:
          </p>
          <div className="grid grid-cols-3 gap-3">
            {Object.entries(CHAT_DESTINATIONS).map(([key, dest]) => (
              <button
                key={key}
                onClick={() => handleOpenDestination(dest.url)}
                className="px-4 py-3 border border-zinc-200 dark:border-zinc-800 rounded-lg hover:border-zinc-300 dark:hover:border-zinc-700 hover:bg-zinc-50 dark:hover:bg-zinc-900 transition-colors text-sm font-medium text-foreground flex flex-col items-center gap-1"
              >
                <span className="text-lg">{dest.icon}</span>
                <span>{dest.name}</span>
              </button>
            ))}
          </div>
        </div>

        <p className="text-xs text-zinc-500 dark:text-zinc-500 mt-4 text-center">
          Context will be copied to your clipboard when you click a destination
        </p>

        {runId && (
          <div className="border-t border-zinc-200 dark:border-zinc-800 pt-4 mt-4">
            <p className="text-xs text-zinc-500 dark:text-zinc-500 mb-2">
              After using this in your chat tool:
            </p>
            <div className="flex gap-2">
              <button
                onClick={handleHarvest}
                className="flex-1 px-3 py-2 text-xs bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-400 hover:bg-green-200 dark:hover:bg-green-900/50 rounded-lg transition-colors"
              >
                Mark Harvested
              </button>
              <button
                onClick={handleAbandon}
                className="flex-1 px-3 py-2 text-xs bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 hover:bg-zinc-200 dark:hover:bg-zinc-700 rounded-lg transition-colors"
              >
                Abandon
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

