// app/privacy/page.tsx
// Privacy Policy page

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[rgb(var(--bg))]">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="prose prose-sm max-w-none text-[rgb(var(--text))]">
          <h1 className="font-serif text-3xl sm:text-4xl font-semibold text-[rgb(var(--text))] mb-4">Privacy Policy — INDEX</h1>
          
          <p className="text-[rgb(var(--muted))] mb-6">
            <strong>Effective Date:</strong> January 8, 2026
          </p>

          <p className="mb-6">
            INDEX ("the app") is a Personal Business Intelligence tool that helps users import, organize, and search AI conversation exports using similarity-based search and reflection affordances.
          </p>

          <section className="mb-8">
            <h2 className="font-serif text-2xl font-semibold text-[rgb(var(--text))] mb-4">1. Data Collection</h2>
            <p className="mb-4">We collect only the data required to operate the service:</p>
            <ul className="list-disc list-inside space-y-2 ml-4 mb-4">
              <li>Email address (via authentication provider)</li>
              <li>Usage signals generated by the app, including imports, searches, highlights, tasks, and decisions</li>
              <li>Content of imported AI conversations, which is <strong>processed for search indexing only</strong> and may be stored in vector-embedding form</li>
            </ul>
            <p className="mb-4">We do <strong>not</strong> collect:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Names beyond authentication email</li>
              <li>Device identifiers outside of essential logs</li>
              <li>Sensitive personal attributes (race, religion, health, sexual orientation, political affiliation, etc.)</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-2xl font-semibold text-[rgb(var(--text))] mb-4">2. Use of Data</h2>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Your data is used <strong>only to provide INDEX functionality</strong></li>
              <li>Imported conversations are indexed to enable semantic search and citation retrieval</li>
              <li>Your data is <strong>not used to train AI models</strong></li>
              <li>We do not share or sell your data for advertising or third-party training</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-2xl font-semibold text-[rgb(var(--text))] mb-4">3. Data Storage</h2>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Data is stored securely using third-party cloud providers</li>
              <li>Vector embeddings are generated via API but contain <strong>no recoverable personal identifiers</strong></li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-2xl font-semibold text-[rgb(var(--text))] mb-4">4. Cookies & Tracking</h2>
            <p className="mb-4">INDEX uses minimal cookies to support authentication and analytics:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>These may include signed-in session cookies and anonymous analytics signals</li>
              <li>We do not track individuals across sites or services</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-2xl font-semibold text-[rgb(var(--text))] mb-4">5. Your Rights</h2>
            <p className="mb-4">You may:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Export your data at any time</li>
              <li>Delete your account and associated data permanently</li>
              <li>Request removal of stored data or embeddings tied to your account</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-2xl font-semibold text-[rgb(var(--text))] mb-4">6. Service Context</h2>
            <p className="mb-4">
              This is an <strong>alpha-stage product</strong>. We operate on a best-effort basis and may update this policy as the app evolves.
            </p>
            <p>
              For questions or deletion requests, contact:{' '}
              <a
                href="mailto:legal@indexapp.co"
                className="text-[rgb(var(--muted))] hover:text-[rgb(var(--text))] underline"
              >
                legal@indexapp.co
              </a>
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
