// app/projects/[id]/components/ProjectStartChatButton.tsx
'use client';

import { useState } from 'react';
import StartChatModal from '@/app/components/StartChatModal';
// Intent descriptions - must match server-side
const INTENT_DESCRIPTIONS: Record<string, string> = {
  decide_between_options: 'Decide between options',
  generate_next_actions: 'Generate next concrete actions',
  resolve_blocking_uncertainty: 'Resolve a blocking uncertainty',
  produce_plan_architecture: 'Produce a plan / architecture',
  stress_test_direction: 'Stress-test current direction',
  summarize_state_propose_path: 'Summarize state → propose path forward',
};

type StartChatIntent = 
  | 'decide_between_options'
  | 'generate_next_actions'
  | 'resolve_blocking_uncertainty'
  | 'produce_plan_architecture'
  | 'stress_test_direction'
  | 'summarize_state_propose_path'
  | 'custom';

interface ProjectStartChatButtonProps {
  projectId: string;
  projectName?: string;
}

export default function ProjectStartChatButton({ projectId, projectName }: ProjectStartChatButtonProps) {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [promptText, setPromptText] = useState<string | null>(null);
  const [runId, setRunId] = useState<string | null>(null);
  const [isExpanded, setIsExpanded] = useState(false);

  const handleCopy = async () => {
    if (!promptText) return;
    
    const timestamp = new Date().toLocaleString();
    const watermark = `\n\n---\nGenerated by INDEX — ${projectName || 'Project'} — ${timestamp}`;
    const textToCopy = promptText + watermark;

    try {
      await navigator.clipboard.writeText(textToCopy);
      if (runId) {
        await fetch(`/api/start-chat/${runId}/update-status`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ status: 'copied' }),
        });
      }
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  if (promptText) {
    const previewText = promptText.substring(0, 200) + (promptText.length > 200 ? '...' : '');
    const displayText = isExpanded ? promptText : previewText;

    return (
      <div className="relative flex items-center gap-2">
        <button
          onClick={handleCopy}
          className="px-3 py-1.5 text-xs bg-foreground text-background rounded-lg hover:opacity-90 transition-opacity font-medium"
        >
          Copy Prompt
        </button>
        <button
          onClick={() => setIsExpanded(!isExpanded)}
          className="text-xs text-zinc-500 dark:text-zinc-500 hover:text-foreground transition-colors"
        >
          {isExpanded ? 'Collapse' : 'Expand details'}
        </button>
        {isExpanded && (
          <div className="absolute top-full right-0 mt-2 w-96 max-w-[calc(100vw-2rem)] p-3 bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg shadow-lg z-50 max-h-96 overflow-y-auto">
            <pre className="text-xs text-zinc-600 dark:text-zinc-400 whitespace-pre-wrap break-words">
              {promptText}
            </pre>
          </div>
        )}
        <button
          onClick={() => {
            setPromptText(null);
            setIsExpanded(false);
            setIsModalOpen(true);
          }}
          className="text-xs text-zinc-500 dark:text-zinc-500 hover:text-foreground transition-colors"
        >
          New
        </button>
      </div>
    );
  }

  return (
    <>
      <button
        onClick={() => setIsModalOpen(true)}
        className="px-3 py-1.5 text-sm border border-zinc-300 dark:border-zinc-700 rounded-lg hover:bg-zinc-50 dark:hover:bg-zinc-900 transition-colors text-foreground"
      >
        Resume
      </button>
      <StartChatModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        contextBlock={{
          project: projectName || undefined,
          source: 'decision',
          summary: 'Resume',
          suggestedExploration: '',
          fullContext: '',
        }}
        runId={null}
        onStatusUpdate={undefined}
        mode="intent-selector"
        onGenerate={async (intent: string, targetTool: string) => {
          try {
            const response = await fetch('/api/start-chat/generate', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                originType: 'project',
                originId: projectId,
                intent,
                targetTool,
              }),
            });

            if (!response.ok) {
              const errorData = await response.json();
              throw new Error(errorData.error || 'Failed to generate prompt');
            }

            const data = await response.json();
            setPromptText(data.promptText);
            setRunId(data.runId);
            setIsModalOpen(false);
          } catch (err) {
            console.error('Failed to generate prompt:', err);
          }
        }}
        projectName={projectName}
      />
    </>
  );
}
